name: master
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build, Test and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.ref }}
            fetch-depth: 0
      - run: |
            git fetch --no-tags --prune --depth=5 origin master        
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Set yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Get yarn cache
        uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-      
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint --base=origin/master
      - name: Format
        run: yarn format:check --base=origin/master
      - name: Test
        run: yarn test
      - name: Build and Deploy --base=origin/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
